name: Pull Latest MDS-Onto from Bitbucket

on:
  schedule:
    # Runs daily at 01:00 UTC. Adjust the cron expression as needed.
    # For example, '0 0 * * *' for midnight UTC, or '0 */6 * * *' for every 6 hours.
    - cron: '0 1 * * *'
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This token is crucial for pushing changes back to the repository
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest stable Python 3 version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 PyGithub packaging

      - name: Run script to pull latest MDS-Onto
        run: python scripts/pull_mds_onto_latest.py
        env:
          # Pass the GitHub PAT to the Python script as an environment variable
          GH_PAT: ${{ secrets.GH_PAT }}
