name: Pull Latest MDS-Onto from Bitbucket

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      # --- OPTIONAL: Explicit initial pull if you suspect checkout isn't fresh enough or for specific merging strategies --- 
      - name: Pull latest changes
        run: git pull --rebase origin main

      - name: Push changes
        run: git push origin main
        # This step should use the same token as checkout if the repo is private or you need authenticated pull
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # Ensure token is available for git pull
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 PyGithub packaging

      - name: Run script to pull latest MDS-Onto
        run: python scripts/pull_mds_onto_latest.py
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      # --- CRUCIAL: Pull again before final push to handle race conditions ---
      - name: Configure Git for final push and rebase
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main # Or master, or your TARGET_BRANCH

      - name: Check for changes and push
        id: push_changes
        run: |
          if ! git diff --quiet HEAD; then
            echo "Changes detected after rebase. Pushing..."
            git push
          else
            echo "No new changes or changes integrated by rebase. Skipping push."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
